# Copyright (C) 1996-1998 Robert H”hne, see COPYING.RH for details 
# This file is part of RHIDE. 
# $Id$
#

srcdir=$(RHIDESRC)/libide/include
VPATH=$(srcdir)

project=

po_files=

src_files=$(po_files)\
	libide.h rawkeys.h tdepende.h tflagcol.h tflagent.h tflaglis.h \
	tideedit.h tidefile.h toptions.h \
	tprjlist.h tprjwind.h tproject.h idecomma.h idefunct.h ideenums.h \
	Makefile makefile.src tfname.h

cfg_files=
update_files=

subdirs=
po_subdirs=

include $(RHIDESRC)/common.mak
