# Copyright (C) 1996-2000 Robert H”hne, see COPYING.RH for details 
# This file is part of RHIDE. 
#

srcdir=$(RHIDESRC)/libide/stream
VPATH=$(srcdir)

project=stream

po_files=

src_files=$(po_files) rhide.env rhide.var\
	sdepcoll.cc sdepende.cc sflagcol.cc sflagent.cc \
	sideedit.cc sidefile.cc soptions.cc sproject.cc \
	Makefile makefile.src stream.gpr stream.mak
cfg_files=
projects=stream

subdirs=
po_subdirs=

include $(RHIDESRC)/common.mak
