#!/bin/sh

# Copyright (C) 1996 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# a little bit modified for RHIDE

if test -r $2; then
  if `cat $2 | cmp $1 > /dev/null`; then
    echo $2 is unchanged
    rm -f $1
  else
    cp -f $1 $2
    rm -f $1
  fi
else
  cp -f $1 $2
  rm -f $1
fi
