# Copyright (C) 1996-1998 Robert H”hne, see COPYING.RH for details 
# This file is part of RHIDE. 

srcdir=$(RHIDESRC)/tvdemo/names
VPATH=$(srcdir)

project=

po_files=

src_files=$(po_files) \
	nascii.cc ncalview.cc ncalwind.cc npuzzlv.cc npuzzlw.cc \
	nreport.cc ntable.cc \
	Makefile makefile.src

cfg_files=
update_files=

subdirs=
po_subdirs=

include $(RHIDESRC)/common.mak
