# Copyright (C) 1996-2000 Robert H”hne, see COPYING.RH for details 
# This file is part of RHIDE. 
#

srcdir=$(RHIDESRC)/libtvuti/names
VPATH=$(srcdir)

project=names

po_files=

src_files=$(po_files) makefile.src rhide.env rhide.var\
	ndirlist.cc nparamli.cc Makefile names.gpr names.mak
cfg_files=
projects=names

subdirs=
po_subdirs=

include $(RHIDESRC)/common.mak
