# Copyright (C) 1996-2000 Robert H”hne, see COPYING.RH for details 
# This file is part of RHIDE. 
#

srcdir=$(RHIDESRC)/librhgdb/test
VPATH=$(srcdir)
project=gsymify

po_files=

src_files=$(po_files) Makefile gsymify.gpr gsymify.mak \
	  listfunc.gpr listfunc.mak mygdb.c mygdb.mak mygdb.gpr \
	  makefile.src rhide.env rhide.var

projects=gsymify listfunc mygdb
cfg_files=

subdirs=
po_subdirs=

include $(RHIDESRC)/common.mak


