# Copyright (C) 1996-2000 Robert H”hne, see COPYING.RH for details 
# This file is part of RHIDE. 
#

srcdir=$(RHIDESRC)/librhgdb/include
VPATH=$(srcdir)

project=

po_files=
src_files=$(po_files) librhgdb.h rhgdbint.h Makefile makefile.src
cfg_files=

subdirs=
po_subdirs=

include $(RHIDESRC)/common.mak

