# Copyright (C) 1996,1997 Robert H”hne, see COPYING.RH for details 
# This file is part of RHIDE. 
#
# $Id$
#

srcdir=$(RHIDESRC)/librhgdb/include
VPATH=$(srcdir)

project=

po_files=
src_files=$(po_files) librhgdb.h rhgdbint.h makefile makefile.src
cfg_files=
update_files=

subdirs=
po_subdirs=

include $(RHIDESRC)/common.mak

