# Copyright (C) 1996-2000 Robert H”hne, see COPYING.RH for details 
# This file is part of RHIDE. 
srcdir=$(RHIDESRC)/debobj
VPATH=$(srcdir)

src_files=Makefile makefile.src
po_files=
cfg_files=

subdirs=
po_subdirs=

include $(RHIDESRC)/common.mak
