# Copyright (C) 1996-1998 Robert H”hne, see COPYING.RH for details 
# This file is part of RHIDE. 
# $Id$
#

srcdir=$(RHIDESRC)/libide/names
VPATH=$(srcdir)

project=names

po_files=

src_files=$(po_files) \
	ndepcoll.cc ndepende.cc nflagcol.cc nflagent.cc \
	nideedit.cc nidefile.cc noptions.cc nproject.cc \
	Makefile makefile.src names.gpr names.mak

cfg_files=
update_files=

subdirs=
po_subdirs=

include $(RHIDESRC)/common.mak
