# Copyright (C) 1996-2000 Robert H”hne, see COPYING.RH for details 
# This file is part of RHIDE. 

srcdir=$(RHIDESRC)/libide/names
VPATH=$(srcdir)

project=names

po_files=

src_files=$(po_files) rhide.env rhide.var\
	ndepcoll.cc ndepende.cc nflagcol.cc nflagent.cc \
	nideedit.cc nidefile.cc noptions.cc nproject.cc \
	Makefile makefile.src names.gpr names.mak

cfg_files=
projects=names

subdirs=
po_subdirs=

include $(RHIDESRC)/common.mak
