/* Copyright (C) 1996-1998 Robert H”hne, see COPYING.RH for details */
/* This file is part of RHIDE. */
F("-gnata")
F("-gnatb")
F("-gnatc")
F("-gnate")
F("-gnatf")
F("-gnatg")
F("-gnatiC")
F("-gnatjE")
F("-gnatkN")
F("-gnatl")
F("-gnatmN")
F("-gnatn")
F("-gnato")
F("-gnatp")
F("-gnatq")
F("-gnatr")
F("-gnats")
F("-gnatt")
F("-gnatu")
F("-gnatv")
F("-gnatwM")
F("-gnatzM")
F("-gnat83")
