/* Copyright (C) 1996-1998 Robert H”hne, see COPYING.RH for details */
/* This file is part of RHIDE. */
F("-ansi")
F("-fallow-single-precision")
F("-fcond-mismatch")
F("-fno-asm")
F("-fno-builtin")
F("-fsigned-bitfields")
F("-fno-signed-bitfields")
F("-funsigned-bitfields")
F("-fno-unsigned-bitfields")
F("-fsigned-char")
F("-funsigned-char")
F("-fwritable-strings")
F("-traditional")
F("-traditional-cpp")
F("-trigraphs")
F("-fhosted")
F("-ffreestanding")

