/* Copyright (C) 1996-1998 Robert H”hne, see COPYING.RH for details */
/* This file is part of RHIDE. */
F("-fno-access-control")
F("-fall-virtual")
F("-fcheck-new")
F("-fconserve-space")
F("-fdollars-in-identifiers")
F("-fenum-int-equiv")
F("-fexternal-templates")
F("-falt-external-templates")
F("-ffor-scope")
F("-fno-for-scope")
F("-fno-gnu-keywords")
F("-fguiding-decls")
F("-fno-implicit-templates")
F("-fhandle-signatures")
F("-fhuge-objects")
F("-fno-implement-inlines")
F("-fmemoize-lookups")
F("-fsave-memoized")
F("-fstrict-prototype")
F("-fname-mangling-version-%d")
F("-fno-nonnull-objects")
F("-foperator-names")
F("-fthis-is-variable")
F("-fvtable-thunks")
F("-ftemplate-depth-%d")
F("-nostdinc++")
F("-traditional")
F("-fno-default-inline")
F("-Wold-style-cast")
F("-Woverloaded-virtual")
F("-Wtemplate-debugging")
F("-Weffc++")
F("+e%d")

