/* Copyright (C) 1996-1998 Robert H”hne, see COPYING.RH for details */
/* This file is part of RHIDE. */
#if 0
/* I remove this now */
F("-fsyntax-only")
#endif
F("-pedantic")
F("-pedantic-errors")
F("-w")
F("-Wno-import")
F("-Wchar-subscripts")
F("-Wcomment")
F("-Wformat")
F("-Wimplicit-int")
F("-Wimplicit-function-declarations")
F("-Wimplicit")
F("-Wmain")
F("-Wparentheses")
F("-Wreturn-type")
F("-Wswitch")
F("-Wtrigraphs")
F("-Wunused")
F("-Wuninitialized")
F("-Wreorder")
F("-Wtemplate-debugging")
F("-Wall")
F("-W")
F("-Wtraditional")
F("-Wundef")
F("-Wshadow")
F("-Wid-clash-%d")
F("-Wlarger-than-%d")
F("-Wpointer-arith")
F("-Wbad-function-cast")
F("-Wcast-qual")
F("-Wcast-align")
F("-Wwrite-strings")
F("-Wconversion")
F("-Wsign-compare")
F("-Waggregate-return")
F("-Wstrict-prototypes")
F("-Wmissing-prototypes")
F("-Wmissing-declarations")
F("-Wredundant-decls")
F("-Wnested-externs")
F("-Winline")
F("-Wold-style-cast")
F("-Woverloaded-virtual")
F("-Wsynth")
F("-Werror")

