# Copyright (C) 1996-1998 Robert H”hne, see COPYING.RH for details 
# This file is part of RHIDE. 
#
# $Id$
#

srcdir=$(RHIDESRC)/include
VPATH=$(srcdir)

project=

src_files=\
	  ideapp.h ideconst.h rhide.h \
	  Makefile rhidehis.h makefile.src
po_files=
cfg_files=
update_files=

subdirs=flags
po_subdirs=

include $(RHIDESRC)/common.mak
